#!/bin/bash

TITLE="$*"
CONTENT="
     #+BEGIN_EXAMPLE
$(cat | sed 's/^/     /g')
     #+END_EXAMPLE
"

if [[ -n $TITLE ]]
then
  CONTENT="   - ${TITLE}\n${CONTENT}"
fi

/usr/local/bin/emacsclient -c -n \
  -e "(progn (org-capture-string \"$CONTENT\" \"C\") (delete-frame))"
